name: PHP Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install
        working-directory: testing/unit testing

      - name: Run PHPUnit with minimum coverage
        working-directory: testing/unit testing
        run: |
          php vendor/bin/phpunit --coverage-text
      
      - name: Run test
        working-directory: "testing/unit testing"
        run: |
          chmod +x vendor/bin/phpunit
          php vendor/bin/phpunit
